---
controller_inventory_sources_all:
  - name: config_as_code_source
    organization: config_as_code
    source: scm
    source_project: config_as_code
    source_path: "inventory_{{ env }}.yml"
    inventory: config_as_code
    credential: ""
    overwrite: true
    overwrite_vars: true
    update_cache_timeout: 0

  - name: devconf_inv_src
    organization: org_unix
    source: scm
    source_project: devconf_prj_inventory
    source_path: "hosts.yml"
    inventory: devconf_test
    credential: ""
    overwrite: true
    overwrite_vars: true
    update_cache_timeout: 0
...
