---
controller_templates_dev:
  - name: jt_configure_rhel86
    project: config_as_code_dev
    job_type: run
    playbook: provision_rhel86.yml
    inventory: devconf_prj_inventory
    execution_environment: supported
    concurrent_jobs_enabled: false
    ask_variables_on_launch: true
    verbosity: 2
    credentials:
      - aap_admin
      - ah_token_user
      - vault
    extra_vars:
      # for debugging errors with creds change to false
      controller_configuration_credentials_secure_logging: true

...
