---
controller_templates_dev:
#Below are dummy JT's for demo.Configure proper playbooks for real scenario
  - name: jt_configure_webserver_devconf
    project: devconf_prj_role
    playbook: provision_webserver_rhel86.yml
    inventory: devconf_test
    execution_environment: 'Control Plane Execution Environment'
    concurrent_jobs_enabled: false
    ask_variables_on_launch: false
    verbosity: 0
    credentials:
      - aap_admin
    extra_vars:
      # for debugging errors with creds change to false
      controller_configuration_credentials_secure_logging: true

  - name: jt_configure_services_devconf
    project: devconf_prj_role
    playbook: provision_services_rhel86.yml
    inventory: devconf_test
    execution_environment: 'Control Plane Execution Environment'
    concurrent_jobs_enabled: false
    ask_variables_on_launch: false
    verbosity: 0
    credentials:
      - aap_admin
    extra_vars:
      # for debugging errors with creds change to false
      controller_configuration_credentials_secure_logging: true

  - name: jt_disable_root_login_devconf
    project: devconf_prj_role
    playbook: failed_services_rhel86.yml
    inventory: devconf_test
    execution_environment: 'Control Plane Execution Environment'
    concurrent_jobs_enabled: false
    ask_variables_on_launch: false
    verbosity: 0
    credentials:
      - aap_admin

  - name: jt_configure_firewall_devconf
    project: devconf_prj_role
    playbook: failed_services_rhel86.yml
    inventory: devconf_test
    execution_environment: 'Control Plane Execution Environment'
    concurrent_jobs_enabled: false
    ask_variables_on_launch: false
    verbosity: 0
    credentials:
      - aap_admin

  - name: jt_disable_unused_services_devconf
    project: devconf_prj_role
    playbook: failed_services_rhel86.yml
    inventory: devconf_test
    execution_environment: 'Control Plane Execution Environment'
    concurrent_jobs_enabled: false
    ask_variables_on_launch: false
    verbosity: 0
    credentials:
      - aap_admin

  - name: jt_update_packages_devconf
    project: devconf_prj_role
    playbook: failed_services_rhel86.yml
    inventory: devconf_test
    execution_environment: 'Control Plane Execution Environment'
    concurrent_jobs_enabled: false
    ask_variables_on_launch: false
    verbosity: 0
    credentials:
      - aap_admin

  - name: jt_failure_message_devconf
    project: devconf_prj_role
    playbook: failed_services_rhel86.yml
    inventory: devconf_test
    execution_environment: 'Control Plane Execution Environment'
    concurrent_jobs_enabled: false
    ask_variables_on_launch: false
    verbosity: 0
    credentials:
      - aap_admin
...
