---
controller_workflows_dev:
  - name: Simple workflow schema
    description: a basic workflow
    inventory: devconf_test
    state: present
    organization: org_unix
    simplified_workflow_nodes:
      - all_parents_must_converge: false
        identifier: jt_configure_webserver_rhel86
        unified_job_template: jt_configure_webserver_rhel86
        success_nodes:
          - jt_configure_services_rhel86
      - all_parents_must_converge: false
        identifier: jt_configure_services_rhel86
        unified_job_template: jt_configure_services_rhel86
