---
controller_workflows_dev:
  - name: Devconf Test Workflow
    description: a testing workflow to demonstrate a working workflow
    inventory: devconf_test
    state: present
    organization: org_unix
    workflow_nodes:
      - all_parents_must_converge: false
        identifier: node101
        unified_job_template: jt_configure_webserver_rhel86
        related:
          success_nodes:
            - jt_configure_services_rhel86
          failure_nodes:
            - jt_failure_message_rhel86
      - all_parents_must_converge: false
        identifier: jt_configure_services_rhel86
        unified_job_template: jt_configure_services_rhel86
