---
controller_workflows_dev:
  - name: wt_devconf_test_demo
    description: a testing workflow to demonstrate a working workflow
    inventory: devconf_test
    state: present
    organization: org_unix
    simplified_workflow_nodes:
      - identifier: jt_configure_webserver_devconf
        unified_job_template: jt_configure_webserver_devconf
        success_nodes:
          - jt_configure_services_devconf

      - identifier: jt_configure_services_devconf
        unified_job_template: jt_configure_services_devconf
        success_nodes:
          - jt_disable_root_login_devconf
        failure_nodes:
          - jt_failure_message_devconf

      - identifier: jt_disable_root_login_devconf
        unified_job_template: jt_disable_root_login_devconf
        success_nodes:
          - jt_configure_firewall_devconf

      - identifier: jt_configure_firewall_devconf
        unified_job_template: jt_configure_firewall_devconf
        success_nodes:
          - jt_disable_unused_services_devconf

      - identifier: jt_disable_unused_services_devconf
        unified_job_template: jt_disable_unused_services_devconf
        success_nodes:
          - jt_update_packages_devconf

      - identifier: jt_update_packages_devconf
        unified_job_template: jt_update_packages_devconf
        failure_nodes:
          - jt_failure_message_devconf

      - identifier: jt_failure_message_devconf
        unified_job_template: jt_failure_message_devconf
